<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8GAKHLN" failures="1" tests="3" name="tests.test1" time="10.509" errors="0" timestamp="16 Jun. 2021 02:02:39 GMT" skipped="0">
  <testcase classname="tests.test1" name="LoginwithEmptyPassword" time="3.470"/>
  <testcase classname="tests.test1" name="LoginwithwrongEmailandPassword" time="3.508">
    <failure message="expected [Wrong Credentials
Invalid username or password] but found [You Can&#039;t Use This Feature Right Now
We limit how often you can post, comment or do other things in a given amount of time in order to help protect the community from spam. You can try again later. Learn More]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Wrong Credentials
Invalid username or password] but found [You Can't Use This Feature Right Now
We limit how often you can post, comment or do other things in a given amount of time in order to help protect the community from spam. You can try again later. Learn More]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.test1page.error(test1page.java:60)
at tests.test1.LoginwithwrongEmailandPassword(test1.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
    </failure>
  </testcase> <!-- LoginwithwrongEmailandPassword -->
  <testcase classname="tests.test1" name="LoginwithEmptyEmail" time="3.531"/>
</testsuite> <!-- tests.test1 -->
